# Generated by Django 5.2.11 on 2026-02-08 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferencePDF",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("s3_key", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_pdfs",
                        to="meta.department",
                    ),
                ),
            ],
        ),
    ]
