# Generated by Django 4.2.18 on 2026-02-09 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referencepdf",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Reference PDF",
                "verbose_name_plural": "Reference PDFs",
            },
        ),
        migrations.RenameField(
            model_name="referencepdf",
            old_name="s3_key",
            new_name="cloudinary_public_id",
        ),
        migrations.RenameField(
            model_name="referencepdf",
            old_name="upload_timestamp",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="referencepdf",
            name="department",
        ),
        migrations.AddField(
            model_name="referencepdf",
            name="cloudinary_url",
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referencepdf",
            name="department_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="referencepdf",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="referencepdf",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
